/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.{html,js}"],
  theme: {
    extend: {
      fontFamily: {
        'geist': ['Geist', 'sans-serif'],
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
  safelist: [
    // Colores personalizados
    'text-[#2563eb]',
    'bg-[#f8f8f8]',
    'text-[#0f172a]',
    'text-[#64748b]',
    'bg-[#f1f5f9]',
    'text-[#7dd3fc]',
    'bg-[#0f172a]',
    'text-[#f8fafc]',
    'bg-[#f8fafc]',
    'text-[#e2e8f0]',
    'bg-[#ffffff]',
    'text-[#1d4ed8]',
    'bg-[#1d4ed8]',
    'text-[#0ea5e9]',
    'text-[#2ab8ff]',
    'text-[#045a85]',
    'text-[#45c1ff]',
    'text-[#1f8dc4]',
    'bg-[#4d85ff]',
    'bg-[#1d4ed8]',
    'bg-[#2568fb]',
    'bg-[#0a3fd2]',
    'bg-[#2ab8ff]',
    'bg-[#045a85]',
    'bg-[#45c1ff]',
    'bg-[#1f8dc4]',
    'bg-[#25D366]',
    'bg-[#f5f5f5]',
    'bg-[#9d9d9d]',
    'bg-[#089ee5]',
    'bg-[#005379]',
    'text-[#25D366]',
    'border-[#2563eb]',
    'border-[#e2e8f0]',
    'border-[#00000014]',
    'shadow-[#00000033]',
    'shadow-[#0000001f]',
    'shadow-[#2563eb4d]',
    'shadow-[#51c8ff4d]',
    
    // Clases de gradientes personalizados
    'gradient-text-modern',
    'btn-primary',
    'btn-secondary',
    'btn-outline',
    
    // Clases de componentes personalizados
    'hero-title',
    'section-title',
    'service-card',
    'certification-card',
    'service-icon',
    'cert-logo',
    'faq-item',
    'faq-question',
    'faq-answer',
    'faq-icon',
    'footer-title',
    'whatsapp-float',
    'section-divider',
    'brand-name',
    'contact-link',
    'nav-link',
    'hamburger-line',
    'navbar-toggler',
    'fade-element',
    'logo-scroller',
    'logo-scroller__inner',
    'tech-carousel-container',
    'tech-carousel-slide',
    'tech-carousel-card',
    'tech-carousel-indicators',
    'tech-indicator',
    
    // Clases de utilidad adicionales
    'max-w-7xl',
    'z-10',
    'z-40',
    'z-1000',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-8',
    'gap-12',
    'rounded-3xl',
    'rounded-full',
    'shadow-lg',
    'shadow-md',
    'animate-bounce',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'tracking-tight',
    'tracking-wider',
    'opacity-0',
    'opacity-1',
    'visible',
    'no-scroll',
    'open'
  ],
  corePlugins: {
    // Desactivar algunos plugins que podrían interferir con nuestros estilos personalizados
    preflight: false,
  }
}